#!/bin/bash
#pushpop

pushd ()
{
    dirname=$1
    if [ -n "$dirname" ] && [ \( -d "$dirname" \) -a \( -x "$dirname" \) ]; then
        DIR_STACK="$dirname ${DIR_STACK:-$PWD" "}" # push the directory
        cd $dirname 
        echo $DIR_STACK
    else
        echo still in $PWD # else do nothing
     fi
}

popd ()
{
    if [ -n "$DIR_STACK" ]; then
        DIR_STACK=${DIR_STACK#* }
        cd ${DIR_STACK%% *}
        echo "$PWD"
    else
        echo "stack empty, still in $PWD."
    fi
}
selectd()
{
    PS3='directory? '
    dirstack=" $DIR_STACK "
    
    select selection in $dirstack; do
        if [ $selection ]; then
            DIR_STACK="$selection${dirstack%% $selection * }"
            DIR_STACK="$DIR_STACK ${dirstack##* $selection }"
            DIR_STACK=${DIR_STACK% }
            cd $selection
            break
        else
            echo 'invalid seletion.'
        fi
   done
}
                

