#!/bin/bash
# regex-match 

# usage: ./regex-match <'pattern'> <words in single quotes, to check for match>
pattern=$1
shift
echo "Matching pattern '$pattern' against strings:"
for string; do # string contains all the command line arguments except the first. The first argumanet <pattern> has be shifted.
    if [ -z "$(echo $string | egrep $pattern)" ]; then            
        printf "%-20s %-10s\n" "$string" ": no match"
    else
        # echo $string | egrep $pattern 
        printf "%-20s %-10s\n" "$string" ": match" 
    fi
done

exit 0

